project 'Smack-2.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smack-2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smack-2
  pod 'Alamofire', '4.5.0'
  pod 'SwiftyJSON', '3.1.4'
  pod 'Socket.IO-Client-Swift'

end
